services:
  app:
    build:
      context: '..'
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    command: sleep infinity
    ports:
      - '8000:8000'
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:v1.8.4
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - '6333:6333'
      - '6334:6334'
    restart: unless-stopped

volumes:
  qdrant_data:
